#!.travis.yml
branches:
  only:
    - master

dist: bionic
sudo: require
language: bash

env:
  global:
    - USER="cfgmgmtcamp"
    - EMAIL="info@cfgmgmtcamp.eu"
    - REPO="cfgmgmtcamp.eu"
    - GH_REPO="github.com/${USER}/${REPO}.git"

install:
  - "sudo apt-get -qq update"
  - "sudo apt-get install --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra texlive-latex-recommended dvipng latex-beamer"

script:
  - export DEBIAN_FRONTEND=noninteractive
  - mkdir _build
  - pdflatex -output-directory=_build -interaction=nonstopmode -file-line-error -no-shell-escape sponsordoc-presentation.tex
  - pdflatex -output-directory=_build -interaction=nonstopmode -file-line-error -no-shell-escape sponsordoc-presentation.tex
  - pdflatex -output-directory=_build -interaction=nonstopmode -file-line-error -no-shell-escape sponsordoc.tex
  - pdflatex -output-directory=_build -interaction=nonstopmode -file-line-error -no-shell-escape sponsordoc.tex

after_success:
  - MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
  - git clone git://${GH_REPO}
  - mkdir -p ${REPO}/static/files/
  - mv -f _build/sponsordoc.pdf ${REPO}/static/files/
  - cd ${REPO}
  - git remote
  - git config user.email ${EMAIL}
  - git config user.name ${USER}
  - git add static/files/sponsordoc.pdf
  - git commit static/files/sponsordoc.pdf -m "${MESSAGE}"
  - git push "https://${GH_TOKEN}@${GH_REPO}" master

deploy:
  provider: releases
  verbose: true
  skip_cleanup: true
  keep-history: true
  api-key: ${GH_TOKEN}
  local-dir: _build
  file:
  - _build/sponsdoc.pdf
  - _build/sponsordoc-presentation.pdf
  on:
    branch: master

