version: 2
jobs:
  build:
    docker:
      - image: blang/latex
    working_directory: ~/cfgmgmtcamp
    steps:
      - checkout
      - run:
          name: "Build PDF file"
          command: make
      - persist_to_workspace:
          root: .
          paths:
            - sponsordoc.pdf

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
  nightly:
    triggers:
      - schedule:
          cron: "1 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
