version: 2
jobs:
  build:
    docker:
      - image: blang/latex
    working_directory: ~/cfgmgmtcamp
    steps:
      - checkout
      - run:
          name: "Build PDF file"
          command: make TMPDIR=/tmp
      - store_artifacts:
          path: /tmp/sponsordoc.pdf
          destination: sponsordoc.pdf
      - store_artifacts:
          path: /tmp/version
          destination: version

  publish-github-release:
    docker:
      - image: cibuilds/github:0.13
    steps:
      - attach_workspace:
          at: /tmp/
      - run:
          name: "Publish Release on GitHub"
          command: |
            TAG=$(cat /tmp/version)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${TAG} /tmp/sponsordoc.pdf

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              only: master
            tags:
              only: /^\d+\.\d+$/

  nightly:
    triggers:
      - schedule:
          cron: "1 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
