name: Build Sponsor Document LaTeX based MASTER
on:
  push:
    branches:
      - main
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: sponsordoc.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: sponsordoc.pdf
          path: sponsordoc.pdf

name: Build Sponsor Document LaTeX base RELEASE
on:
  push:
    tags:
      - '*'
jobs:
  deploy:
    name: Create Release
    needs: build_latex
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Update to Sponsordoc ${{ github.ref }}
          draft: false
          prerelease: false
