name: Build MASTER Sponsor Document LaTeX based
on:
  push:
    branches:
      - master
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Install TexLive packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: git bash texlive-full
          version: latest
      - name: Update all git information
        run: git fetch --tags
      - name: Compile LaTeX document
        run: make
        #uses: xu-cheng/latex-action@v3
        #with:
        #  root_file: sponsordoc.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: sponsordoc
          path: sponsordoc.pdf
