name: Build MASTER Sponsor Document LaTeX based
on:
  push:
    branches:
      - master
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        run: make
        #with:
        #  root_file: sponsordoc.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: sponsordoc
          path: sponsordoc.pdf
