name: Build MASTER Sponsor Document LaTeX based
on:
  push:
    branches:
      - master
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Update apt-get Caches
        run: sudo apt-get update
      - name: Install TexLive packages
        run: sudo apt-get -y install texlive-full
      - name: Print latest git tag
        run: git describe --abbrev=0 --tags --always
      - name: Compile LaTeX document
        run: make
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: sponsordoc
          path: sponsordoc.pdf
