name: Build TAG Sponsor Document LaTeX base
on:
  push:
    tags:
      - '*'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - id: latexdoc
        name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: sponsordoc.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: sponsordoc
          path: sponsordoc.pdf
    outputs:
      pdffile: ${{ steps.latexdoc.outputs.sponsordoc }}
  deploy:
    name: Create Release
    needs: build_latex
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.build_latex.outputs.pdffile }}
